### PR TITLE
Upgrade Rails to v5.1 plus test with Rails 5.2

### PR DESCRIPTION
**Pull request by etagwerker**
Hi there,

This PR upgrades Rails to 5.1. Please check it out. Thanks! 

I will abide by the [code of conduct](code_of_conduct.md).

### CODE REVIEW

**Comment by lubc** [comment]
@kindoflew Could you QA this locally (I think we don't have a staging instance of it) to check that everything works normally? Thanks!

**Comment by kindoflew** [comment]
Finally got the app to work locally. I had to add specific Rails versions to the `db` migration classes (ie `class CreateUsers < ActiveRecord::Migration[5.1]`).

While pairing with Francois to troubleshoot my issues, we also came across problems with setting up the database. In `config/database.yml` we changed the following to get it to work:

```diff
  development:
-   database: <%= ENV['DATABASE_NAME'] %>_test
    <<: *default
+   database: <%= ENV['DATABASE_NAME'] %>_dev

  test:
    <<: *default
+   database: <%= ENV['DATABASE_NAME'] %>_test

  production:
    <<: *default
```

I'm not sure if the original is a bug in the syntax, but Francois says it is.

Anyways:
* Once I got it up and running, everything worked as expected! So, that's cool.
* Should I push the `config/databse.yml` changes to this PR?

**Comment by fbuys** [comment]
> @etagwerker I believe another part of the issue we found was that `<<: *default` needed to be before `database: <%= ENV['DATABASE_NAME'] %>_dev`(Unless I misunderstood, maybe @fbuys can confirm?).

Yes, my perception is that adding the `<<: *default` at the end overwrites values with default values. We want to do the opposite, we want overwrite the default values with custom environment values.

**Comment by etagwerker** [comment]
> @etagwerker are the changes to config/databse.yml necessary for the upgrade? 

@bronzdoc It was brought up by @kindoflew in this comment: https://github.com/fastruby/pecas/pull/90#issuecomment-944454041 

It looked like a simple error so I fixed it. Now that they have created an issue for it (https://github.com/fastruby/pecas/issues/92) I removed that commit from this branch. 

> I can add a PR for those changes if everyone is happy to split this PR?

@fbuys Sounds good.

**Review by lubc — CHANGES_REQUESTED** [review]
@etagwerker I'm getting this error when setting up the project:

```
== Preparing database ==
Created database 'pecas'
Database 'pecas' already exists
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
/Users/lubc/projects/ombulabs/pecas/db/migrate/20150716174838_create_users.rb:1:in `<top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
/Users/lubc/projects/ombulabs/pecas/db/migrate/20150716174838_create_users.rb:1:in `<top (required)>'
Tasks: TOP => db:migrate
```

Looks like you need to update the migration files

**Comment by etagwerker** [comment]
@lubc Good find! I just updated the migration files. 👍

**Review by lubc — APPROVED** [review]
@etagwerker QA looks good!

**Pull request merged**
